"""Typed Pydantic models for ``specialist_outputs.output_json`` rows.

Each pipeline specialist writes a JSON artifact in ``.apply-state/``; the
ingest hook serialises that artifact into the ``output_json`` column.  This
module owns the *shape* of those artifacts so that ``deserialize_output``
returns a typed model regardless of caller.

Adding a new specialist
-----------------------
1. Add a Pydantic class describing the output shape.
2. Register it in ``KIND_MODELS`` under the kind string.
3. Add the artifact filename → (kind, reader) entry to
   ``jobsmith._state_readers.ARTIFACT_READERS`` so the ingest hook knows
   how to load the file.
"""
from __future__ import annotations

import sqlite3
from typing import Any

from pydantic import BaseModel, Field


class JDParsed(BaseModel):
    """kind=jd-parsed."""

    company: str | None = None
    position: str | None = None
    location: str | None = None
    location_type: str | None = None
    salary_range: str | None = None
    req_id: str | None = None
    apply_url: str | None = None
    role_type: str | None = None
    jd_text_clean: str | None = None
    must_haves: list[str] = Field(default_factory=list)
    nice_to_haves: list[str] = Field(default_factory=list)
    top_keywords: list[str] = Field(default_factory=list)


class FitScore(BaseModel):
    """kind=fit-score."""

    score: float | None = None
    score_raw: float | None = None
    rationale: str | None = None
    specialty: str | None = None
    confidence: str | None = None
    must_have_table: list[dict[str, Any]] = Field(default_factory=list)
    matched_evidence: list[str] = Field(default_factory=list)
    concerns: list[str] = Field(default_factory=list)
    pitch: str | None = None


class BulletSelection(BaseModel):
    """kind=bullet-selection."""

    positions: list[dict[str, Any]] = Field(default_factory=list)
    anchor_bullets_master: list[Any] = Field(default_factory=list)
    anchor_bullets_kept: list[Any] = Field(default_factory=list)
    anchor_bullets_dropped: list[Any] = Field(default_factory=list)


class HMSnippet(BaseModel):
    """kind=hm-snippet."""

    detected: bool = False
    name: str | None = None
    source: str | None = None
    one_specific_signal: str | None = None
    suggested_hook: str | None = None


class TextArtifact(BaseModel):
    """Generic text-only artifact (prose-draft, company-research, outreach-snippets)."""

    text: str | None = None


class AITellReport(BaseModel):
    """kind=ai-tell-report."""

    iterations: list[dict[str, Any]] = Field(default_factory=list)


class ATSCheck(BaseModel):
    """kind=ats-check."""

    score: float | None = None
    issues: list[str] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# New kinds added in feat-ca7408db: cover-letter-draft, quarto-config,
# variables, manifest, anchor-check, fact-check
# ---------------------------------------------------------------------------


class CoverLetterDraft(BaseModel):
    """kind=cover-letter-draft.

    The humanised cover-letter text written by apply-cover-letter-writer
    (or edited by the user).  Stored at <app>/cover-letter-draft.md and,
    when a humanizer pass runs, also at <app>/.apply-state/cover-letter-draft.md.
    The ``text`` field holds the raw markdown content.
    """

    text: str | None = None


class QuartoConfig(BaseModel):
    """kind=quarto-config.

    The ``_quarto.yml`` content generated by :func:`jobsmith.assemble.assemble`
    that turns each application directory into a Quarto project.  The
    ``content`` field holds the raw YAML text so it can be replayed during
    Phase 3 snapshot regeneration without re-running assemble.
    """

    content: str | None = None


class Variables(BaseModel):
    """kind=variables.

    The ``_variables.yml`` scalars assembled from jd-parsed + fit-score +
    hm-snippet + bullet-selection artifacts.  Stored as a flat/nested dict
    so individual fields (company, position, fit.score, etc.) are queryable
    from the DB without parsing YAML.

    The full dict is permissive (``extra="allow"``) because the variable
    shape evolves as new specialists are added.
    """

    model_config = {"extra": "allow"}

    slug: str | None = None
    company: str | None = None
    position: str | None = None
    fit: dict[str, Any] = Field(default_factory=dict)
    jd: dict[str, Any] = Field(default_factory=dict)
    bullets: dict[str, Any] = Field(default_factory=dict)
    hm: dict[str, Any] = Field(default_factory=dict)


class Manifest(BaseModel):
    """kind=manifest.

    The orchestrator-written ``manifest.json`` that tracks run metadata and
    specialist invocation outcomes.  This is the authoritative in-flight
    state document; DB rows supersede it for completed phases.
    """

    run_id: str | None = None
    slug: str | None = None
    started_at: str | None = None
    finished_at: str | None = None
    invocations: list[dict[str, Any]] = Field(default_factory=list)


class AnchorCheck(BaseModel):
    """kind=anchor-check.

    Result of the ``jobsmith anchor-check`` guardrail that verifies
    high-signal anchor bullets are preserved in the tailored selection.
    ``exit_code`` mirrors the CLI exit code: 0 = pass, 1 = dropped anchor
    without reason, 2 = internal error.
    """

    exit_code: int = 0
    dropped_without_reason: list[str] = Field(default_factory=list)
    message: str | None = None


class FactCheck(BaseModel):
    """kind=fact-check.

    Result of the ``jobsmith fact-check`` guardrail that verifies hard
    claims in the drafted cover letter are grounded in the master YAML
    content files.  ``passed`` is True when every extracted claim is
    verified against at least one master file.
    """

    passed: bool = True
    failed_claims: list[str] = Field(default_factory=list)
    verified_count: int = 0


#: Maps the ``kind`` column to the Pydantic class used by ``deserialize_output``.
KIND_MODELS: dict[str, type[BaseModel]] = {
    # gather phase
    "jd-parsed": JDParsed,
    "fit-score": FitScore,
    "bullet-selection": BulletSelection,
    "hm-snippet": HMSnippet,
    "company-research": TextArtifact,
    # draft phase
    "prose-draft": TextArtifact,
    "ai-tell-report": AITellReport,
    # render phase
    "ats-check": ATSCheck,
    "anchor-check": AnchorCheck,
    "fact-check": FactCheck,
    # assemble outputs (written to <app>/ rather than .apply-state/)
    "cover-letter-draft": CoverLetterDraft,
    "quarto-config": QuartoConfig,
    "variables": Variables,
    # orchestrator
    "outreach-snippets": TextArtifact,
    "manifest": Manifest,
}


def deserialize_output(row: sqlite3.Row) -> BaseModel:
    """Deserialise a ``specialist_outputs`` row into a typed model.

    Falls back to :class:`TextArtifact` for unknown kinds so callers never
    need to handle ``None``.
    """
    model_cls = KIND_MODELS.get(row["kind"], TextArtifact)
    return model_cls.model_validate_json(row["output_json"])


__all__ = [
    "AITellReport",
    "ATSCheck",
    "AnchorCheck",
    "BulletSelection",
    "CoverLetterDraft",
    "FactCheck",
    "FitScore",
    "HMSnippet",
    "JDParsed",
    "KIND_MODELS",
    "Manifest",
    "QuartoConfig",
    "TextArtifact",
    "Variables",
    "deserialize_output",
]
