// views.tsx — port of design/app/views.jsx
//
// Exports: SiteView, FeedbackView, DoctorView, ConfigView

import { useState } from 'react';
import { Icon, Badge, SAMPLE_APPS } from './shared';

// ── SiteView ─────────────────────────────────────────────────────────────

type SiteMode = 'public' | 'private';

export function SiteView() {
  const apps = SAMPLE_APPS.filter(a => a.status === 'rendered');
  const [mode, setMode] = useState<SiteMode>('public');

  return (
    <div className="content">
      <div className="page-head">
        <div>
          <h1>listings site</h1>
          <p>a quarto-rendered index of every assembled application — share-ready, with a private mode for personal review.</p>
        </div>
        <div className="actions">
          <div style={{ display: 'flex', gap: 0, border: '1px solid var(--border-strong)', borderRadius: 'var(--radius)', overflow: 'hidden' }}>
            {(['public', 'private'] as SiteMode[]).map(m => (
              <span
                key={m}
                className="mono-sm"
                onClick={() => setMode(m)}
                style={{
                  padding: '6px 12px',
                  cursor: 'pointer',
                  background: mode === m ? 'var(--bg-sunk)' : 'var(--bg-elev)',
                  color: mode === m ? 'var(--fg)' : 'var(--fg-muted)',
                  borderRight: m === 'public' ? '1px solid var(--border)' : 'none',
                  fontSize: 12,
                }}
              >
                {m}
              </span>
            ))}
          </div>
          <button className="btn"><Icon name="play" size={12} /> serve</button>
          <button className="btn primary"><Icon name="site" size={12} /> render</button>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 320px', gap: 16 }}>
        <div className="card" style={{ overflow: 'hidden' }}>
          <div className="card-h" style={{ background: 'var(--bg-sunk)' }}>
            <div style={{ display: 'flex', gap: 6 }}>
              <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#ff5f56' }}></span>
              <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#ffbd2e' }}></span>
              <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#27c93f' }}></span>
            </div>
            <div className="mono-sm" style={{ marginLeft: 14, color: 'var(--fg-muted)' }}>
              {mode === 'public' ? 'jordan-smith.dev/applications' : 'localhost:4200 (private)'}
            </div>
          </div>
          <div style={{ padding: '40px 56px', background: 'var(--bg-elev)', minHeight: 520 }}>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--fg-subtle)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 14 }}>jordan smith · applications</div>
            <div style={{ fontSize: 32, fontWeight: 600, letterSpacing: '-0.025em', marginBottom: 6 }}>open applications</div>
            <div style={{ color: 'var(--fg-muted)', fontSize: 14, marginBottom: 32, maxWidth: 520 }}>
              every role i'm interested in, with the resume + cover i actually sent — generated by jobsmith and rendered through quarto.
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 0, borderTop: '1px solid var(--border)' }}>
              {apps.map(a => (
                <div
                  key={a.slug}
                  style={{
                    padding: '18px 0',
                    borderBottom: '1px solid var(--border)',
                    display: 'grid',
                    gridTemplateColumns: '1fr auto auto',
                    gap: 18,
                    alignItems: 'center',
                  }}
                >
                  <div>
                    <div style={{ fontSize: 16, fontWeight: 500, letterSpacing: '-0.005em' }}>{a.role}</div>
                    <div style={{ color: 'var(--fg-muted)', fontSize: 13, marginTop: 2 }}>{a.company} · sent {a.updated}</div>
                    {mode === 'private' && (
                      <div className="mono-sm" style={{ color: 'var(--fg-subtle)', marginTop: 4 }}>{a.slug}</div>
                    )}
                  </div>
                  <div style={{ display: 'flex', gap: 6 }}>
                    {a.renders.map(r => (
                      <span key={r} className="badge" style={{ cursor: 'pointer' }}>
                        <Icon name="doc" size={10} /> {r}
                      </span>
                    ))}
                  </div>
                  <Icon name="arrow" size={14} style={{ color: 'var(--fg-subtle)' }} />
                </div>
              ))}
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div className="card">
            <div className="card-h"><h3>render mode</h3></div>
            <div style={{ padding: '14px 16px', fontSize: 13, color: 'var(--fg-muted)', lineHeight: 1.55 }}>
              {mode === 'public'
                ? <span><b style={{ color: 'var(--fg)' }}>public</b> strips private-tagged variables (slug, drop reasons, internal notes) before rendering.</span>
                : <span><b style={{ color: 'var(--fg)' }}>private</b> renders everything — slugs, fact-check trails, anchor coverage. for your eyes only.</span>}
            </div>
          </div>

          <div className="card">
            <div className="card-h"><h3>last render</h3><span className="sub mono-sm">2.4s</span></div>
            <div style={{ padding: '14px 16px', fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--fg-muted)', lineHeight: 1.9 }}>
              <div><Icon name="check" size={11} style={{ color: 'var(--success)', marginRight: 6 }} />quarto render</div>
              <div><Icon name="check" size={11} style={{ color: 'var(--success)', marginRight: 6 }} />5 listings indexed</div>
              <div><Icon name="check" size={11} style={{ color: 'var(--success)', marginRight: 6 }} />10 PDFs copied</div>
              <div><Icon name="check" size={11} style={{ color: 'var(--success)', marginRight: 6 }} />sitemap.xml written</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// ── FeedbackView ─────────────────────────────────────────────────────────

interface FeedbackRow {
  slug: string;
  date: string;
  kind: 'edit' | 'outcome';
  summary: string;
  tag: string;
}

const FEEDBACK_ROWS: FeedbackRow[] = [
  { slug: 'anthropic-applied-ai-2026-04',       date: '2026-04-30', kind: 'edit',    summary: 'tightened cover paragraph 2; reduced from 4 sentences to 3.',               tag: 'cover'   },
  { slug: 'vercel-platform-eng-2026-04',         date: '2026-04-30', kind: 'edit',    summary: 'swapped scheduler-migration for live-reload-dev-env; better fit.',           tag: 'bullets' },
  { slug: 'resend-developer-experience-2026-03', date: '2026-04-12', kind: 'outcome', summary: 'phone screen scheduled.',                                                    tag: 'outcome' },
  { slug: 'render-cli-2026-03',                  date: '2026-04-08', kind: 'outcome', summary: 'on-site invite.',                                                             tag: 'outcome' },
  { slug: 'fly-systems-2026-03',                 date: '2026-04-02', kind: 'outcome', summary: 'rejection (no reason cited).',                                               tag: 'outcome' },
  { slug: 'stripe-infra-2026-03',                date: '2026-04-01', kind: 'edit',    summary: 'rephrased "1.2B requests" as "billion-scale" — too specific.',               tag: 'voice'   },
];

export function FeedbackView() {
  const rows = FEEDBACK_ROWS;

  return (
    <div className="content">
      <div className="page-head">
        <div>
          <h1>feedback</h1>
          <p>captured edits and outcomes per slug. trains the bullet-selector and cover-drafter over time.</p>
        </div>
        <div className="actions">
          <button className="btn"><Icon name="doc" size={13} /> export json</button>
          <button className="btn"><Icon name="x" size={13} /> prune</button>
          <button className="btn primary"><Icon name="plus" size={13} /> record</button>
        </div>
      </div>

      <div className="stat-row" style={{ gridTemplateColumns: 'repeat(3, 1fr)' }}>
        <div className="stat">
          <div className="label">total entries</div>
          <div className="value">{rows.length}</div>
          <div className="delta">across 6 slugs</div>
        </div>
        <div className="stat">
          <div className="label">edits captured</div>
          <div className="value">{rows.filter(r => r.kind === 'edit').length}</div>
          <div className="delta">↓ 2 vs last month</div>
        </div>
        <div className="stat">
          <div className="label">outcomes</div>
          <div className="value">{rows.filter(r => r.kind === 'outcome').length}</div>
          <div className="delta up">2 advanced to interview</div>
        </div>
      </div>

      <div className="card">
        <div className="card-h">
          <h3>recent entries</h3>
          <span className="sub mono-sm">private/feedback.db</span>
        </div>
        <table className="table">
          <thead>
            <tr><th>date</th><th>slug</th><th>kind</th><th>summary</th><th>tag</th></tr>
          </thead>
          <tbody>
            {rows.map((r, i) => (
              <tr key={i} className="row-clickable">
                <td><span className="mono-sm" style={{ color: 'var(--fg-subtle)' }}>{r.date}</span></td>
                <td><span className="slug">{r.slug}</span></td>
                <td>{r.kind === 'outcome' ? <Badge kind="success">outcome</Badge> : <Badge kind="accent">edit</Badge>}</td>
                <td style={{ fontSize: 13 }}>{r.summary}</td>
                <td><Badge>{r.tag}</Badge></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// ── DoctorView ───────────────────────────────────────────────────────────

interface DoctorCheck {
  name: string;
  status: 'ok' | 'warn';
  detail: string;
}

const DOCTOR_CHECKS: DoctorCheck[] = [
  { name: 'claude CLI',             status: 'ok',   detail: 'v1.4.0 at /usr/local/bin/claude' },
  { name: 'quarto',                 status: 'ok',   detail: 'v1.5.57' },
  { name: '.apply-config.yaml',     status: 'ok',   detail: 'valid · schema v3' },
  { name: 'master/work.yml',        status: 'ok',   detail: '38 bullets · 14 anchors marked' },
  { name: 'master/skill.yml',       status: 'ok',   detail: '12 groups' },
  { name: 'master/education.yml',   status: 'ok',   detail: '2 entries' },
  { name: 'benchmark.md',           status: 'warn', detail: 'present but last edited 4 months ago' },
  { name: 'private/jobsmith.db',    status: 'ok',   detail: 'open · 8 prior runs' },
  { name: 'private/feedback.db',    status: 'ok',   detail: 'open · 6 entries' },
  { name: 'plugin/system-prompts/', status: 'ok',   detail: '3 phase prompts found' },
  { name: 'plugin/agents/',         status: 'ok',   detail: '8 specialist contracts found' },
];

export function DoctorView() {
  const checks = DOCTOR_CHECKS;

  return (
    <div className="content">
      <div className="page-head">
        <div>
          <h1>doctor</h1>
          <p>preflight environment checks. the same set <span className="mono">jobsmith doctor</span> runs from the CLI.</p>
        </div>
        <div className="actions">
          <button className="btn primary"><Icon name="play" size={12} /> re-run checks</button>
        </div>
      </div>
      <div className="card">
        <table className="table">
          <thead>
            <tr>
              <th style={{ width: '24%' }}>check</th>
              <th>detail</th>
              <th style={{ width: 120 }}>status</th>
            </tr>
          </thead>
          <tbody>
            {checks.map(c => (
              <tr key={c.name}>
                <td><span className="mono-sm">{c.name}</span></td>
                <td style={{ color: 'var(--fg-muted)', fontSize: 13 }}>{c.detail}</td>
                <td>{c.status === 'ok' ? <Badge kind="success">ok</Badge> : <Badge kind="warn">warn</Badge>}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// ── ConfigView ───────────────────────────────────────────────────────────

export function ConfigView() {
  return (
    <div className="content">
      <div className="page-head">
        <div>
          <h1>config</h1>
          <p>workspace settings — written to <span className="mono">.apply-config.yaml</span>.</p>
        </div>
        <div className="actions">
          <button className="btn"><Icon name="doc" size={13} /> validate</button>
          <button className="btn primary"><Icon name="check" size={12} /> save</button>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
        <div className="card">
          <div className="card-h"><h3>workspace</h3></div>
          <div style={{ padding: '16px 18px' }}>
            <div className="field"><label>author</label><input className="mono" defaultValue="jordan-smith" /></div>
            <div className="field"><label>applications dir</label><input className="mono" defaultValue="applications/" /></div>
            <div className="field"><label>private dir</label><input className="mono" defaultValue="private/" /></div>
            <div className="field"><label>phase timeout (s)</label><input className="mono" defaultValue="600" /></div>
          </div>
        </div>
        <div className="card">
          <div className="card-h"><h3>master files</h3></div>
          <div style={{ padding: '16px 18px' }}>
            <div className="field"><label>work</label><input className="mono" defaultValue="master/work.yml" /></div>
            <div className="field"><label>skills</label><input className="mono" defaultValue="master/skill.yml" /></div>
            <div className="field"><label>education</label><input className="mono" defaultValue="master/education.yml" /></div>
            <div className="field"><label>author</label><input className="mono" defaultValue="master/author.yml" /></div>
            <div className="field"><label>benchmark</label><input className="mono" defaultValue="master/benchmark.md" /></div>
          </div>
        </div>
      </div>
    </div>
  );
}
